set(comp0037_reactive_planner_controller_MESSAGE_FILES "")
set(comp0037_reactive_planner_controller_SERVICE_FILES "/home/ros_user/cw2_catkin_ws/src/comp0037/comp0037_reactive_planner_controller/srv/Goal.srv")
